siteTitle = "Diegesis - Readable versions of Greek Histories"
siteDescr = "Diegesis is a library of ancient Grecian classis formatted to be legible and easy to read"
siteAuthor = "Alex Boerstler"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = "/lumen"
